<?php



function notification_update_nodes_theme($existing, $type, $theme, $path) {
  return [
    'email_update' => [
      'variables' => [
        'bundle' => null,
        'id' => null,
        'title' => null
      ],
      'template' => 'email-update',
    ],
  ];
}

/**
 * Implements hook_entity_update().
 */
function notification_update_nodes_entity_update(Drupal\Core\Entity\EntityInterface $entity) {
  // Vérifie si l'entité est de type 'node' (vous pouvez modifier cela selon vos besoins).
  if ($entity->getEntityTypeId() == 'node') {
    $contentType = $entity->bundle();
    $nodeId = $entity->id();
    $nodeTitle = $entity->label();
    $contentType = $entity->bundle();
    $mailManager = \Drupal::service('notification.email_service');
    $mailManager->envoyerEmail($contentType,$nodeId,$nodeTitle);
  }
}

/**
 * Implements hook_mail().
 */
function notification_update_nodes_mail($key, &$message, $params) {
  switch ($key) {
    case 'content_update_notification':
      // Définit le sujet de l'e-mail.
      $message['subject'] = $params['subject'];
      // Définit le corps de l'e-mail.
      $message['body'][] = $params['body'];
      $message['headers']['Content-Type'] = 'text/html; charset=UTF-8';
      break;
  }
}
